# Use a more recent Node.js runtime as a parent image
FROM node:16

# Set the working directory
RUN mkdir -p /app
WORKDIR /app

# Copy the package.json and package-lock.json
COPY package.json package-lock.json /app/

# Install dependencies
RUN npm install

# Create a dedicated volume for node_modules to prevent local development overwrites
VOLUME /app/node_modules

# Copy the rest of the application code to the working directory
COPY . /app

# Command to start the application
CMD ["npm", "start"]
